# Generated by Django 4.0.1 on 2022-03-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_VIDEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_server_name', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('connected_lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lectureapp.all_lectures')),
            ],
        ),
    ]
