# Generated by Django 4.0.1 on 2022-03-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureapp', '0004_all_lectures_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_lectures',
            name='files',
            field=models.FileField(null=True, upload_to='lecturefiles/', verbose_name=''),
        ),
    ]
