# Generated by Django 4.0.1 on 2022-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_forums',
            name='forum_answers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='all_forums',
            name='forum_question',
            field=models.TextField(),
        ),
    ]
