# Generated by Django 4.0.1 on 2022-03-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVAILABLE_COURSES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('lecture_series_number', models.IntegerField(default=0)),
                ('test_series_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CLASS_COURSES_MAPPING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=7)),
                ('course_id_array', models.CharField(max_length=100)),
            ],
        ),
    ]
