# Generated by Django 4.0.1 on 2022-03-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_courses',
            name='course_instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginapp.user_signup_database'),
        ),
    ]
