# Generated by Django 4.0.1 on 2022-03-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_remove_user_signup_database_class_course_field'),
        ('courseapp', '0003_available_courses_forum_series_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_courses',
            name='course_instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginapp.teacher_code_mapping'),
        ),
        migrations.AlterField(
            model_name='class_courses_mapping',
            name='unique_id',
            field=models.CharField(max_length=8),
        ),
    ]
