# Generated by Django 4.0.1 on 2022-03-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUERY_DATABASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date_time', models.DateTimeField(auto_now_add=True)),
                ('query_email_address', models.EmailField(max_length=254)),
                ('query_url', models.CharField(default=None, max_length=100)),
                ('query_description', models.CharField(max_length=500)),
                ('query_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='USER_SIGNUP_DATABASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('user_class', models.CharField(max_length=2)),
                ('user_section', models.CharField(max_length=1)),
                ('user_contact', models.CharField(max_length=11)),
                ('user_r_number', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=100)),
                ('user_category', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('class_course_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courseapp.class_courses_mapping')),
            ],
        ),
    ]
