# Generated by Django 4.0.1 on 2022-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_DATABASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_email', models.EmailField(max_length=254)),
                ('assigned_OTP', models.CharField(max_length=8)),
                ('assigned_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
