# Generated by Django 4.0.1 on 2022-03-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_remove_user_signup_database_class_course_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup_database',
            name='verfied_user',
            field=models.BooleanField(default=False),
        ),
    ]
