# Generated by Django 4.0.1 on 2022-03-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_alter_available_courses_course_instructor_and_more'),
        ('loginapp', '0007_remove_user_signup_database_class_course_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_code_mapping',
            name='teacher_mapping',
        ),
        migrations.AddField(
            model_name='teacher_code_mapping',
            name='teacher_assigned_class',
            field=models.CharField(default=10, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_code_mapping',
            name='teacher_assigned_section',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_code_mapping',
            name='teacher_assigned_subject',
            field=models.CharField(default='SC', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_signup_database',
            name='class_course_field',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.class_courses_mapping'),
        ),
        migrations.AddField(
            model_name='user_signup_database',
            name='connected_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.teacher_code_mapping'),
        ),
        migrations.AddField(
            model_name='user_signup_database',
            name='user_created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
