# Generated by Django 4.0.1 on 2022-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_remove_teacher_code_mapping_teacher_mapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_code_mapping',
            name='teacher_assigned_section',
            field=models.CharField(max_length=2),
        ),
    ]
