# Generated by Django 4.0.1 on 2022-03-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_alter_teacher_code_mapping_teacher_assigned_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup_database',
            name='user_section',
            field=models.CharField(max_length=2),
        ),
    ]
