# Generated by Django 4.0.1 on 2022-03-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_alter_user_signup_database_user_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query_database',
            name='query_url',
        ),
        migrations.AddField(
            model_name='query_database',
            name='query_name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='query_database',
            name='query_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_signup_database',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user_signup_database',
            name='school_name',
            field=models.TextField(),
        ),
    ]
