# Generated by Django 4.0.1 on 2022-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_remove_query_database_query_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup_database',
            name='password',
            field=models.BinaryField(max_length=256),
        ),
    ]
